/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class juvavum_graph_BlissGraph_Vertex */

#ifndef _Included_juvavum_graph_BlissGraph_Vertex
#define _Included_juvavum_graph_BlissGraph_Vertex
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
