/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class juvavum_graph_BlissGraph */

#ifndef _Included_juvavum_graph_BlissGraph
#define _Included_juvavum_graph_BlissGraph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     juvavum_graph_BlissGraph
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_juvavum_graph_BlissGraph_create
  (JNIEnv *, jobject);

/*
 * Class:     juvavum_graph_BlissGraph
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_juvavum_graph_BlissGraph_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     juvavum_graph_BlissGraph
 * Method:    _add_vertex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_juvavum_graph_BlissGraph__1add_1vertex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     juvavum_graph_BlissGraph
 * Method:    _add_edge
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_juvavum_graph_BlissGraph__1add_1edge
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     juvavum_graph_BlissGraph
 * Method:    _find_automorphisms
 * Signature: (JLjuvavum/graph/BlissGraph/Reporter;)V
 */
JNIEXPORT void JNICALL Java_juvavum_graph_BlissGraph__1find_1automorphisms
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     juvavum_graph_BlissGraph
 * Method:    _canonical_labeling
 * Signature: (JLjuvavum/graph/BlissGraph/Reporter;)[I
 */
JNIEXPORT jintArray JNICALL Java_juvavum_graph_BlissGraph__1canonical_1labeling
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
